# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The `weight` parameter defines the order of the header links.

main:
  - name: Home
    url: '#main'
    weight: 10
  - name: People
    url: '#people'
    weight: 20
  - name: Meetings
    url: '#meetings'
    weight: 40
  - name: Publications
    url: '#publications'
    weight: 50
  - name: Proposals
    url: '#proposals'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
